# Generated by Django 2.2.4 on 2019-08-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gpioPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('func1', models.CharField(max_length=32)),
                ('func2', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('connectable', models.BooleanField()),
            ],
        ),
    ]
