# Generated by Django 2.2.4 on 2019-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpiopin',
            name='row',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
