# Generated by Django 2.2.4 on 2019-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio_manager', '0002_gpiopin_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpiopin',
            name='device',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpiopin',
            name='mqtt_alias',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
