# Generated by Django 2.2.4 on 2019-08-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio_manager', '0005_auto_20190829_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpiopin',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
