# Generated by Django 2.2.4 on 2019-08-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpio_manager', '0006_auto_20190829_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpiopin',
            name='gpio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
